### ISSUE TITLE
Audit Argument Checks

### ISSUE THREAD

**Issue by rtcwp07** [usefulio/connectivity#3]
Thanks for this great package.  Looks like it doesn't pass audit-argument-checks currently.  Might be worth it to at least add a Match.Any to the ping method:

```
check(arguments, [Match.Any])
```

This is the exception I'm seeing:

```
Exception while invoking method 'connectivity.ping' Error: Did not check() all arguments during call to 'connectivity.ping'
```

Thanks again for the great work.

**Comment by vladbalan** [comment]
@rtcwp07 Thank you for your feedback! We're glad you liked this package. You can now find the patched version on Atmosphere.
